config/routes.rb
Rails.application.routes.draw do
  root to:"todo_items#index"
  # get 'todo_items/index'

  # get 'todo_items/show'

  # get 'todo_items/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todo_items

end

# Jareds-MacBook-Pro:todo jared$ rake routes
# Prefix Verb   URI Pattern              Controller#Action
# todo_index GET    /todo(.:format)          todo#index
#        POST   /todo(.:format)          todo#create
# new_todo GET    /todo/new(.:format)      todo#new
# edit_todo GET    /todo/:id/edit(.:format) todo#edit
#   todo GET    /todo/:id(.:format)      todo#show
#        PATCH  /todo/:id(.:format)      todo#update
#        PUT    /todo/:id(.:format)      todo#update
#        DELETE /todo/:id(.:format)      todo#destroy

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  def index
    # local var is only available in the method
    # if we want our view to have access to the var
    # we need an instance variable
    @todos = TodoItem.all
    # SELECT * FROM Pages
    # render :index #this is here automatically
  end

  # responsible for showing a specific page
  def show
    @todos = TodoItem.find(params[:id])
    # default action: render :show - app/views/pages/show.html.erb
  end

  # responsible for showing a form to edit an existing page
  def edit
    @todo = TodoItem.find(params[:id]) # this wants to call an "update" method. see bundle exec rails routes to see why
    # default action: render :show - app/views/pages/show.html.erb
  end

  def update
    @todo = TodoItem.find(params[:id])
    if @todo.update(todo_item_params)
      # success
      redirect_to todo_item_path(@todo) #rails magically supplies the ID
    else
      # fail
      render :edit
    end 

  end

  # responsible for showing a form to create a new page
  def new
    @todo = TodoItem.new
    # render :new - app/views/pages/new.html.erb
  end

  # responsible for saving a new record in our database
  def create
    #strong params
    todo = TodoItem.new(todo_item_params) # just a method that we write in our controllers
    # this executes the sql to try to save the new page in the database
    if todo.save # if we save the page
      #success - new record in the database
      redirect_to todo_item_path(todo) # rails is smart enough to generate the id . we use "page_path" because we just tack on "_path" to the rightmost
      # column for the path we want to access
    else
      # fail - failed to execute the sql for some reason
      render :new
    end
  end

  def destroy
    page = TodoItem.find(params[:id])
    page.destroy
    redirect_to root_path # back to the index page. can also use "root path"
  end

  private
  # strong params
  def todo_item_params
    params.require(:todo_item).permit(:title, :body, :completed) # gives us a hash with all our data, restricts it for security purposes
    #params.require(:page) gives us the same things as params[:page], then it's limited by the "requirex`"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_items/edit.html.erb
<h1>ToDo#edit</h1>
<h1> Editing: <%= @todo.title %> </h1>

<%= form_for @todo do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Title', required: true %>
    <br />
  
    <%= f.label :body, placeholder: 'Additional details', required:true %>
    <%= f.text_field :body %>
    <br />

    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <br />

    <%= f.submit %>
<% end %>

app/views/todo_items/index.html.erb
<h1>TodoItems#index</h1>
<p>Find me in app/views/todo_items/index.html.erb</p>

<%= link_to 'New ToDo Item',  new_todo_item_path %>
<hr />

<% @todos.each do |todo| %>
    <div>
        <h3><%= link_to todo.title, todo_item_path(todo) %></h3>
        
        <i>Title: <%= todo.title %></i>
        <!-- <p>Body: <%= todo.body %></p> -->
        <strong>Completed?: <%= todo.completed ? 'Yes' : 'No' %></strong>

        <%= link_to 'Delete', todo_item_path(todo), method: :delete %>
    </div>
    <hr />
<% end %>

app/views/todo_items/new.html.erb
<h1>TodoItems#new</h1>

<%= form_for @todo do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: 'Title', required: true %>
    <br />
  
    <%= f.label :body, placeholder: 'Additional details', required:true %>
    <%= f.text_field :body %>
    <br />

    <%= f.label :completed %>
    <%= f.check_box :completed %>
    <br />

    <%= f.submit %>
<% end %>

app/views/todo_items/show.html.erb
<h1>TodoItems#show</h1>

<h1><%= @todos.title %></h1>
<i>Title: <%= @todos.title %></i>
<br />
<i>Created: <%= @todos.created_at %> </i>
<hr />
<p><%= @todos.body =%></p>

<%= link_to 'Edit', edit_todo_item_path(@todos) %>

<%= link_to 'Back', root_path %>

<p>Find me in app/views/todo_items/show.html.erb</p>